#pragma once


// An enum that represents all the characters in the game
enum class CharacterId
{
    Goku_Early = 0,
    Goku_Middle_Normal,
    Goku_Middle_SSJ1,
    Goku_End_Normal,
    Goku_End_SSJ1,
    Goku_End_SSJ2,
    Goku_End_SSJ3,
    Goku_GT_Normal,
    Goku_GT_SSJ1,
    Goku_GT_SSJ3,
    Goku_GT_SSJ4,
    Goku_Kid_Normal,
    Goku_Kid_Great_Ape,
    Gohan_Kid,
    Teen_Gohan_Normal,
    Teen_Gohan_SSJ1,
    Teen_Gohan_SSJ2,
    Gohan_Normal,
    Gohan_SSJ1,
    Gohan_SSJ2,
    Gohan_Great_Saiyaman,
    Gohan_Ultime,
    Piccolo_Early,
    Piccolo_End,
    Nail,
    Krillin,
    Yamcha,
    Tenshinhan,
    Chaozu,
    Vegeta_Scouter_Normal,
    Vegeta_Scouter_Great_Ape,
    Vegeta_Normal,
    Vegeta_SSJ1,
    Vegeta_Super_SSJ1,
    Vegeta_2nd_Normal,
    Vegeta_2nd_SSJ1,
    Vegeta_2nd_SSJ2,
    Vegeta_2nd_Majin,
    Vegeta_2nd_SSJ4,
    Trunks_Sword_Normal,
    Trunks_Sword_SSJ1,
    Trunks_Normal,
    Trunks_SSJ1,
    Trunks_Super_SSJ1,
    Trunks_Kid_Normal,
    Trunks_Kid_SSJ1,
    Goten_Normal,
    Goten_SSJ1,
    Gotenks_Normal,
    Gotenks_SSJ1,
    Gotenks_SSJ3,
    Vegito_Normal,
    Vegito_SSJ1,
    Gogeta_SSJ1,
    Gogeta_SSJ4,
    Hercule,
    Videl_Normal,
    Videl_Great_Saiyaman,
    Kaioshin_Normal,
    Kaiobito_Kaioshin,
    Yajirobe,
    Paikuhan,
    Tapion,
    Pan,
    Uub_Normal,
    Uub_Majuub,
    Roshi_Normal,
    Roshi_Max_Power,
    Grandpa_Gohan,
    Nam,
    Android_8,
    King_Vegeta_Normal,
    King_Vegeta_Great_Ape,
    Bardock_Normal,
    Bardock_Great_Ape,
    Fasha_Normal,
    Fasha_Great_Ape,
    Raditz_Normal,
    Raditz_Great_Ape,
    Saibaman,
    Nappa_Normal,
    Nappa_Great_Ape,
    Zarbon_Normal,
    Zarbon_Transformed,
    Dodoria,
    Cui,
    Ginyu,
    Recoome,
    Burter,
    Jeice,
    Guldo,
    Frieza_1st_Form,
    Frieza_2nd_Form,
    Frieza_3rd_Form,
    Frieza_Final_Form,
    Frieza_Full_Power,
    Mecha_Frieza,
    King_Cold,
    Appule,
    Frieza_Solider,
    Android_16,
    Android_17,
    Android_18,
    Android_19,
    Dr_Gero,
    Imperfect_Cell,
    Semi_Perfect_Cell,
    Perfect_Cell,
    Super_Perfect_Cell,
    Cell_Junior,
    Babbidi,
    Dabura,
    Buu,
    Evil_Buu,
    Super_Buu,
    Super_Buu_Gotenks,
    Super_Buu_Gohan,
    Kid_Buu,
    Garlic_Junior,
    Super_Garlic_Junior,
    Dr_Wheelo,
    Turles_Normal,
    Turles_Great_Ape,
    Slug_Normal,
    Slug_Giant,
    Salza,
    Cooler_Normal,
    Cooler_Final_Form,
    Metal_Cooler,
    Android_13_Normal,
    Android_13_Fusion,
    Broly_Normal,
    Broly_SSJ1,
    Broly_Legendray_SSJ,
    Zangya,
    Bojack_Normal,
    Bojack_Transformed,
    Janemba,
    Super_Janemba,
    Hildegan,
    Baby_Vegeta,
    Baby_1_Vegeta,
    Baby_2_Vegeta,
    Baby_Vegeta_Great_Ape,
    Super_17,
    Nuova_Shenron,
    Syn_Shenron_Normal,
    Syn_Shenron_Li_Shenron,
    Tao_Pai_Pai_Normal,
    Tao_Pai_Pai_Cyborg,
    General_Blue,
    Diableman,
    Pilaf_Robot_Normal,
    Pilaf_Robot_Fusion,
    Tambourine,
    Demon_Piccolo,
    Arale,
    Chichi,
    Spopovitch,
    Future_Gohan_Normal,
    Future_Gohan_SSJ1,
    NUM_CHARACTERS
};


enum class BaseCharacterId
{
    Unset = -1,
    Goku_Early,
    Kid_Gohan,
    Piccolo_Early,
    Vegeta_Scouter,
    Krillin,
    Yamcha,
    Trunks_Sword,
    Goku_Mid,
    Teen_Gohan,
    Piccolo_End,
    Vegeta,
    Tien,
    Chiaotzu,
    Trunks,
    Goku_End,
    Gohan,
    Ultimate_Gohan,
    Vegeta_Second_Form,
    Vegeta_End,
    Goten,
    Kid_Trunks,
    Goku_GT,
    Future_Gohan,
    Videl,
    Hercule,
    Vegeta_SSJ4,
    Uub,
    Pan,
    Master_Roshi,
    Yajirobe,
    Nail,
    Supreme_Kai,
    Raditz,
    Nappa,
    Saibamen,
    Captain_Ginyu,
    Recoome,
    Burter,
    Jeice,
    Guldo,
    Zarbon,
    Dodoria,
    Frieza,
    Mecha_Frieza,
    Appule,
    Cui,
    Frieza_Soldier,
    King_Cold,
    King_Vegeta,
    Cell,
    Cell_Jr,
    Dr_Gero,
    Android_19,
    Android_18,
    Android_17,
    Android_16,
    Majin_Buu,
    Majin_Buu_Pure_Evil,
    Super_Buu,
    Kid_Buu,
    Babidi,
    Spopovich,
    Demon_King_Dabura,
    Bardock,
    Fasha,
    Garlic_Jr,
    Dr_Wheelo,
    Turles,
    Slug,
    Salza,
    Cooler,
    Meta_Cooler,
    Android_13,
    Broly,
    Zangya,
    Bojack,
    Janemba,
    Pikkon,
    Tapion,
    Hirudegarn,
    Baby_Vegeta,
    Super_Android_17,
    Nuova_Shenron,
    Syn_Shenron,
    Demon_King_Piccolo,
    Tambourine,
    Pilaf_Machine,
    Devilman,
    General_Blue,
    General_Tao,
    Cyborg_Tao,
    Kid_Goku,
    Chi_Chi,
    Grandpa_Gohan,
    Nam,
    Android_8,
    Arale,
    NUM_BASE_CHARACTERS
};


// A struct that represents the data of a character
struct CharacterData
{
    CharacterId     mId;
    BaseCharacterId mBaseId;
    const char*     mName;
    long long       mPower;
};


namespace charUtils
{
    int CalculateLevel(long long power);
    int CalculateBars(int level);
} // namespace charUtils


// A class that represents a character in the game
class Character
{
public:
    Character() = default;
    Character(const CharacterData& data);

    CharacterId      GetId() const;
    BaseCharacterId  GetBaseId() const;
    int              GetIndex() const;
    int              GetBaseIndex() const;
    const char*      GetName() const;
    long long        GetPower() const;
    int              GetLevel() const;
    int              GetHelthBars() const;

private:
    CharacterData        mData;
    int                  mLevel;
    int                  mHealthBars;
};